export const ADD_EXPRIENCE_REQUEST = "ADD_EXPRIENCE_REQUEST"
export const ADD_EXPRIENCE_SUCCESS = "ADD_EXPRIENCE_SUCCESS"
export const ADD_EXPRIENCE_FAILED = "ADD_EXPRIENCE_FAILED"

export const VIEW_EXPERIENCE_REQUEST = "VIEW_EXPERIENCE_REQUEST"
export const VIEW_EXPERIENCE_SUCCESS = "VIEW_EXPERIENCE_SUCCESS"
export const VIEW_EXPERIENCE_FAILED = "VIEW_EXPERIENCE_FAILED"