export const VIEW_PERSONALINFO_REQUEST = "VIEW_PERSONALINFO_REQUEST"
export const VIEW_PERSONALINFO_SUCCESS = "VIEW_PERSONALINFO_SUCCESS"
export const VIEW_PERSONALINFO_FAILED = "VIEW_PERSONALINFO_FAILED"

export const UPDATE_PERSONALINFO_REQUEST = "UPDATE_PERSONALINFO_REQUEST"
export const UPDATE_PERSONALINFO_SUCCESS = "UPDATE_PERSONALINFO_SUCCESS"
export const UPDATE_PERSONALINFO_FAILED = "UPDATE_PERSONALINFO_FAILED"

export const VIEW_DOCTORINFO_REQUEST = "VIEW_DOCTORINFO_REQUEST"
export const VIEW_DOCTORINFO_SUCCESS = "VIEW_DOCTORINFO_SUCCESS"
export const VIEW_DOCTORINFO_FAILED = "VIEW_DOCTORINFO_FAILED"

export const UPDATE_DOCTORINFO_REQUEST = "UPDATE_DOCTORINFO_REQUEST"
export const UPDATE_DOCTORINFO_SUCCESS = "UPDATE_DOCTORINFO_SUCCESS"
export const UPDATE_DOCTORINFO_FAILED = "UPDATE_DOCTORINFO_FAILED"

export const CHANGE_DOCTOR_PROFILE_REQUEST = "CHANGE_DOCTOR_PROFILE_REQUEST"
export const CHANGE_DOCTOR_PROFILE_SUCCESS = "CHANGE_DOCTOR_PROFILE_SUCCESS"
export const CHANGE_DOCTOR_PROFILE_FAILED = "CHANGE_DOCTOR_PROFILE_FAILED"

export const ADD_EXPERIENCE_REQUEST = "ADD_EXPERIENCE_REQUEST"
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS"
export const ADD_EXPERIENCE_FAILED = "ADD_EXPERIENCE_FAILED"

export const UPDATE_EXPERIENCE_REQUEST = "UPDATE_EXPERIENCE_REQUEST"
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS"
export const UPDATE_EXPERIENCE_FAILED = "UPDATE_EXPREIENCE_FAILED"

export const VIEW_EXPERIENCE_REQUEST = "VIEW_EXPERIENCE_REQUEST"
export const VIEW_EXPERIENCE_SUCCESS = "VIEW_EXPERIENCE_SUCCESS"
export const VIEW_EXPERIENCE_FAILED = "VIEW_EXPERIENCE_FAILED"

export const DELETE_EXPERIENCE_REQUEST = "DELETE_EXPERIENCE_REQUEST"
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS"
export const DELETE_EXPERIENCE_FAILED = "DELETE_EXPERIENCE_FAILED"

export const VIEW_QUALIFICATION_REQUEST = "VIEW_QUALIFICATIONE_REQUEST"
export const VIEW_QUALIFICATION_SUCCESS = "VIE_WQUALIFICATIONE_SUCCESS"
export const VIEW_QUALIFICATION_FAILED = "VIEW_QUALIFICATION_FAILED"

export const UPDATE_QUALIFICATION_REQUEST = "UPDATE_QUALIFICATIONE_REQUEST"
export const UPDATE_QUALIFICATION_SUCCESS = "UPDATE_QUALIFICATIONE_SUCCESS"
export const UPDATE_QUALIFICATION_FAILED = "UPDATE_QUALIFICATION_FAILED"


