export const ADD_EXPRIENCE_REQUEST = "ADD_EXPRIENCE_REQUEST"
export const ADD_EXPRIENCE_SUCCESS = "ADD_EXPRIENCE_SUCCESS"
export const ADD_EXPRIENCE_FAILED = "ADD_EXPRIENCE_FAILED"

export const VIEW_EXPERIENCE_REQUEST = "VIEW_EXPERIENCE_REQUEST"
export const VIEW_EXPERIENCE_SUCCESS = "VIEW_EXPERIENCE_SUCCESS"
export const VIEW_EXPERIENCE_FAILED = "VIEW_EXPERIENCE_FAILED"

export const VIEW_QUALIFICATION_REQUEST = "VIEW_QUALIFICATIONE_REQUEST"
export const VIEW_QUALIFICATION_SUCCESS = "VIE_WQUALIFICATIONE_SUCCESS"
export const VIEW_QUALIFICATION_FAILED = "VIEW_QUALIFICATION_FAILED"

export const VIEW_DOCTORINFO_REQUEST = "VIEW_DOCTORINFO_REQUEST"
export const VIEW_DOCTORINFO_SUCCESS = "VIEW_DOCTORINFO_SUCCESS"
export const VIEW_DOCTORINFO_FAILED = "VIEW_DOCTORINFO_FAILED"

export const VIEW_DOCTOR_REQUEST = "VIEW_DOCTORINFO_REQUEST"
export const VIEW_DOCTOR_SUCCESS = "VIEW_DOCTORINFO_SUCCESS"
export const VIEW_DOCTOR_FAILED = "VIEW_DOCTORINFO_FAILED"