export const FIND_DOCTOR_REQUEST = "FIND_DOCTOR_REQUEST"
export const FIND_DOCTOR_SUCCESSFUL = "FIND_DOCTOR_SUCCESSFUL"
export const FIND_DOCTOR_FAILED = "FIND_DOCTOR_FAILED"

export const   DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST"
export const   DOCTOR_LIST_SUCCESSFUL = "DOCTOR_LIST_SUCCESSFUL"
export const   DOCTOR_LIST_FAILED = "DOCTOR_LIST_FAILED"

export const   SEARCH_CATEGORY_REQUEST = "SEARCH_CATEGORY_REQUEST"
export const   SEARCH_CATEGORY_SUCCESS = "SEARCH_CATEGORY_SUCCESS"
export const   SEARCH_CATEGORY_FAILED = "SEARCH_CATEGORY_FAILED"

export const   DOCTOR_PROFILE_REQUEST = "DOCTOR_PROFILE_REQUEST"
export const   DOCTOR_PROFILE_SUCCESS = "DOCTOR_PROFILE_SUCCESS"
export const   DOCTOR_PROFILE_FAILED = "DOCTOR_PROFILE_FAILED"

export const   DOCTOR_INFO_REQUEST = "DOCTOR_INFO_REQUEST"
export const   DOCTOR_INFO_SUCCESS = "DOCTOR_INFO_SUCCESS"
export const   DOCTOR_INFO_FAILED = "DOCTOR_INFO_FAILED"

export const   DOCTOR_REQUEST = "DOCTOR_REQUEST"
export const   DOCTOR_SUCCESS = "DOCTOR_SUCCESS"
export const   DOCTOR_FAILED = "DOCTOR_FAILED"

export const   DOCTOR_QUALIFICATION_REQUEST = "DOCTOR_QUALIFICATION_REQUEST"
export const   DOCTOR_QUALIFICATION_SUCCESS = "DOCTOR_QUALIFICATION_SUCCESS"
export const   DOCTOR_QUALIFICATION_FAILED = "DOCTOR_QUALIFICATION_FAILED"

export const   SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const   SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const   SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED"

export const   GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST"
export const   GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS"
export const   GET_MESSAGE_FAILED = "GET_MESSAGE_FAILED"

