export const FIND_DOCTOR_REQUEST = "FIND_DOCTOR_REQUEST"
export const FIND_DOCTOR_SUCCESSFUL = "FIND_DOCTOR_SUCCESSFUL"
export const FIND_DOCTOR_FAILED = "FIND_DOCTOR_FAILED"

export const   DOCTOR_LIST_REQUEST = "DOCTOR_LIST_REQUEST"
export const   DOCTOR_LIST_SUCCESSFUL = "DOCTOR_LIST_SUCCESSFUL"
export const   DOCTOR_LIST_FAILED = "DOCTOR_LIST_FAILED"

export const   SEARCH_CATEGORY_REQUEST = "SEARCH_CATEGORY_REQUEST"
export const   SEARCH_CATEGORY_SUCCESS = "SEARCH_CATEGORY_SUCCESS"
export const   SEARCH_CATEGORY_FAILED = "SEARCH_CATEGORY_FAILED"


