export const DOCTOR_SIGNUP_REQUEST = 'DOCTOR_SIGNUP_REQUEST'
export const DOCTOR_SIGNUP_SUCCESS = 'DOCTOR_SIGNUP_SUCCESS'
export const DOCTOR_SIGNUP_FAILED = 'DOCTOR_SIGNUP_FAIL'

export const PATIENT_SIGNUP_REQUEST = 'PATIENT_SIGNUP_REQUEST'
export const PATIENT_SIGNUP_SUCCESS = 'PATIENT_SIGNUP_SUCCESS'
export const PATIENT_SIGNUP_FAILED = 'PATIENT_SIGNUP_FAILED'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const USER_LOGOUT = 'USER_LOGOUT'